// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slqwresfemfcstogutwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNscXdyZXNmZW1mY3N0b2d1dHdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNDM2OTAsImV4cCI6MjA2NzgxOTY5MH0.Bj_2MoT0C712MXq5tr3pVpuCa93aDAOhAjQYhB0Uz8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});